mysql> select *  from students where not  Country in ('Sint Maarten', 'Haiti');
+----+----------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------+
| id | name                 | classroom | notes                                                                                                                                                                                                                                        | City         | Country       |
+----+----------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------+
|  3 | Corena Edgeson       | 1A        | Cannot get enough of data                                                                                                                                                                                                                    | Philadelphia | United States |
|  4 | Archaimbaud Lougheid | 2A        | Would rather do nothing other than sit down in front of a mountain of data and read through it like a book. SERIOUSLY needs to seek help about this because there is no way it is healthy for this person to like data any more than they do | DC           | Brazil        |
|  5 | Dun Pettet           | 2A        | NULL                                                                                                                                                                                                                                         | Newark       | France        |
|  6 | Hymie Parrington     | 2A        | Enjoys the Star Wars prequels                                                                                                                                                                                                                | Lewes        | Denmark       |
+----+----------------------+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+---------------+
4 rows in set (0.00 sec)